In [7]:
import pandas as pd

In [8]:
df = pd.read_csv('./data/imdb_cleaned_data.csv', index_col=0)

In [9]:
df.columns

Index(['budget', 'genres', 'id', 'imdb_id', 'original_title', 'overview',
       'popularity', 'poster_path', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'tagline', 'title', 'vote_average', 'vote_count',
       'log_popularity', 'title_length', 'num_languages', 'num_genres',
       'imdb_rating', 'imdb_budget', 'imdb_revenue', 'budget_currency',
       'revenue_currency', 'converted_budget', 'converted_revenue',
       'combined_budget', 'combined_revenue'],
      dtype='object')

In [10]:
# Make a new dataframe with only columns where 'imdb_budget', 'combined_budget', and 'combined_revnue' are not null in df
df_new = df[df['imdb_budget'].notnull() & df['combined_budget'].notnull() & df['combined_revenue'].notnull()]

In [11]:
display(df.describe())
df_new.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count,log_popularity,title_length,num_languages,num_genres,imdb_rating,imdb_budget,imdb_revenue,converted_budget,converted_revenue,combined_budget,combined_revenue
count,1.145100e+05,114510.000000,114510.000000,1.145100e+05,114510.000000,114510.000000,114510.000000,114510.000000,114510.000000,114510.000000,114510.000000,65595.000000,1.601200e+04,7.816000e+03,1.572300e+04,7.816000e+03,1.145100e+05,1.145100e+05
mean,8.444914e+05,384367.768614,1.818294,2.196408e+06,60.554519,2.883022,58.220016,0.722145,20.092333,1.069321,1.414095,6.188033,9.800112e+06,3.281577e+07,6.849666e+06,3.279686e+07,9.661237e+05,2.277751e+06
std,8.136329e+06,228412.700872,14.718161,2.872709e+07,62.431853,3.251524,567.137737,0.544416,12.201338,0.343558,0.777596,1.359172,2.470047e+08,1.053340e+08,2.088283e+07,1.053263e+08,8.254022e+06,2.879730e+07
min,0.000000e+00,8.000000,0.600000,-1.200000e+01,0.000000,0.000000,0.000000,0.470004,1.000000,1.000000,1.000000,1.000000,1.000000e+00,9.000000e+00,1.024212e-03,9.000000e+00,0.000000e+00,-1.200000e+01
25%,0.000000e+00,193088.500000,0.600000,0.000000e+00,9.000000,0.000000,0.000000,0.470004,12.000000,1.000000,1.000000,5.400000,2.000000e+04,5.118350e+04,2.000000e+04,5.118350e+04,0.000000e+00,0.000000e+00
50%,0.000000e+00,384425.000000,0.600000,0.000000e+00,61.000000,0.000000,0.000000,0.470004,17.000000,1.000000,1.000000,6.300000,3.000000e+05,8.995270e+05,3.000000e+05,8.995270e+05,0.000000e+00,0.000000e+00
75%,0.000000e+00,581657.250000,1.024000,0.000000e+00,92.000000,6.000000,3.000000,0.705076,25.000000,1.000000,2.000000,7.100000,3.000000e+06,1.577630e+07,3.000000e+06,1.574741e+07,0.000000e+00,0.000000e+00
max,5.000000e+08,775592.000000,3907.516000,2.116000e+09,9000.000000,10.000000,27894.000000,8.270913,204.000000,9.000000,8.000000,10.000000,3.000000e+10,2.178630e+09,3.500000e+08,2.178630e+09,5.000000e+08,2.147315e+09

,budget,id,popularity,revenue,runtime,vote_average,vote_count,log_popularity,title_length,num_languages,num_genres,imdb_rating,imdb_budget,imdb_revenue,converted_budget,converted_revenue,combined_budget,combined_revenue
count,1.601200e+04,16012.000000,16012.000000,1.601200e+04,16012.000000,16012.000000,16012.000000,16012.000000,16012.000000,16012.000000,16012.000000,13894.000000,1.601200e+04,4.088000e+03,1.572300e+04,4.088000e+03,1.601200e+04,1.601200e+04
mean,5.843834e+06,285933.520047,5.467451,1.513871e+07,72.810330,4.035474,357.523170,1.181744,16.634149,1.171996,1.799213,6.071002,9.800112e+06,6.007347e+07,6.849666e+06,6.007347e+07,6.713689e+06,1.549069e+07
std,2.056723e+07,248495.362220,36.560436,7.516671e+07,42.811942,2.998174,1469.334378,0.933648,9.880027,0.556715,0.998890,1.476596,2.470047e+08,1.397694e+08,2.088283e+07,1.397694e+08,2.067506e+07,7.526949e+07
min,0.000000e+00,8.000000,0.600000,0.000000e+00,0.000000,0.000000,0.000000,0.470004,1.000000,1.000000,1.000000,1.100000,1.000000e+00,3.000000e+01,1.024212e-03,3.000000e+01,0.000000e+00,0.000000e+00
25%,0.000000e+00,42080.750000,0.600000,0.000000e+00,34.000000,0.000000,0.000000,0.470004,10.000000,1.000000,1.000000,5.200000,2.000000e+04,3.895968e+05,2.000000e+04,3.895968e+05,1.800000e+04,0.000000e+00
50%,0.000000e+00,250346.000000,1.025000,0.000000e+00,87.000000,5.000000,3.000000,0.705570,14.000000,1.000000,1.000000,6.200000,3.000000e+05,1.025499e+07,3.000000e+05,1.025499e+07,2.750000e+05,0.000000e+00
75%,5.000000e+05,499163.500000,4.856250,0.000000e+00,99.000000,6.392000,47.000000,1.767509,20.000000,1.000000,2.000000,7.100000,3.000000e+06,5.192746e+07,3.000000e+06,5.192746e+07,3.000000e+06,2.144475e+04
max,4.600000e+08,775565.000000,3907.516000,2.116000e+09,900.000000,10.000000,27894.000000,8.270913,112.000000,8.000000,8.000000,10.000000,3.000000e+10,2.178630e+09,3.500000e+08,2.178630e+09,4.050000e+08,2.147315e+09

In [12]:
df_new.to_csv('./data/nan_removed_cleaned_data.csv', index=False)